name: "Repository Gardening"
description: "Do things in your GitHub repo"
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ${{ github.token }}
runs:
  using: node16
  main: "dist/index.js"
