name: Bug Report
description: Tell me everything. Is the sky falling on your head, or is it just a bug in the code?
labels: [ 'Needs triage', '[Type] Bug' ]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: A clear and concise description of what you expected to happen.
      placeholder: |
        eg. Post should be liked.
  - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        eg. Clicking the button does nothing visibly.
  - type: textarea
    id: other
    attributes:
      label: Other information
      placeholder: Screenshots, additional logs, notes, etc.
  - type: markdown
    attributes:
      value: |
        ## Issue severity

        Please provide details around how big the problem is.
  - type: dropdown
    id: users-affected
    attributes:
      label: Severity
      description: How many users are impacted? A guess is fine.
      options:
        - One
        - Some (< 50%)
        - Most (> 50%)
        - All
  - type: dropdown
    id: workarounds
    attributes:
      label: Available workarounds?
      options:
        - No and the platform is unusable
        - No but the platform is still usable
        - Yes, difficult to implement
        - Yes, easy to implement
        - There is no user impact
  - type: textarea
    id: workarounds-detail
    attributes:
      label: Workaround details
      description: If you are aware of a workaround, please describe it below.
      placeholder: |
        e.g. There is an alternative way to access this setting in the sidebar, but it's not readily apparent.
