name: Build
on:
  push:
    branches:
      - 'trunk'
      # The `**/*/` works around the fact that GitHub considers a leading `**/` as meaning "zero or more path components" where we want "one or more".
      - '**/*/branch-**'
  pull_request:
concurrency:
  # Cancel concurrent jobs on pull_request but not push, by including the run_id in the concurrency group for the latter.
  group: build-${{ github.event_name == 'push' && github.run_id || 'pr' }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all projects
    runs-on: ubuntu-latest
    timeout-minutes: 20  # 2022-02-10: We've gotten the build down to ~9-15 minutes now! p9dueE-4dJ-p2
    env:
      # Hard-code a specific directory to avoid paths in vendor/composer/installed.json changing every build.
      BUILD_BASE: /tmp/jetpack-build
      TEST_COMMENT_INDICATOR: "<!-- wpcom-reminder-comment -->"
    outputs:
      any_plugins: ${{ steps.plugins.outputs.any }}

    steps:
      - uses: actions/checkout@v3

      - name: Detect changed projects
        id: changed
        run: |
          echo "::set-output name=projects::['plugins/jetpack','plugins/boost']"

      - name: Check if a WordPress.com test reminder comment is needed.
        id: check-test-reminder-comment
        uses: actions/github-script@v6
        env:
          TOUCHED_PROJECTS: '${{ steps.changed.outputs.projects }}'
        if: ${{ github.event_name == 'pull_request' }}
        with:
          result-encoding: string
          script: |
            const checkTestReminderComment = require('.github/actions/build/check-test-reminder-comment.js')
            const commentId = await checkTestReminderComment( github, context, core );

      - name: Other build steps happen here
        run: |
            echo 'Building Jetpack...'
      
      - name: Update reminder with testing instructions
        id: update-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && steps.check-test-reminder-comment.outputs.result != 0 }}
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          COMMENT_ID: ${{ steps.set-reminder-comment.outputs.result }}
        with:
          script: |
            const { BRANCH_NAME, COMMENT_ID, TEST_COMMENT_INDICATOR } = process.env;
            const commentBody = `${ TEST_COMMENT_INDICATOR }
            Are you an Automattician? You can now test your Pull Request on WordPress.com. On your sandbox, run \`bin/jetpack-downloader test jetpack ${ BRANCH_NAME }\` to get started.`;
            await github.rest.issues.updateComment( {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
              comment_id: COMMENT_ID,
            } );

