name: Testing things

on:
  pull_request:

jobs:
  getting-context:
    name: Getting context info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Getting context info
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo "PR title: $PR_TITLE"
      
    - name: Getting context info differently
      uses: actions/github-script@v6
      id: pr-title-script
      with:
        result-encoding: string
        script: |
          return github.context.issue.title

    - name: Get the context from the previous step.
      env:
        NEW_PR_TITLE: ${{ steps.pr-title-script.outputs.result }}
      run: |
        echo "PR title: $NEW_PR_TITLE"