name: Unit Tests

on: [ push, pull_request ]

jobs:
  test:
    name: PHPUnit (${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 3  # Successful runs seem to take ~1 minute

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '5.6', '7.4', '8.0' ]
        experimental: [ false ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          extensions: mysql, imagick
        env:
         update: true # specify true or false

      - name: Tool versions
        run: |
          which php
          php --version
          which composer
          composer --version
          which jq
          jq --version