name: Testing setup-php
on: push
jobs:
  test:
    name: Installing (${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'